trigger:
  branches:
    include:
      - main

stages:
  - stage: Validate
    displayName: Validate bundle
    jobs:
      - job: validate
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          # ✅ Instalar Databricks CLI (Go)
          - script: |
              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
              databricks version
            displayName: Install Databricks CLI (Go)

          - script: |
              set -euxo pipefail
              export DATABRICKS_HOST=$(DATABRICKS_HOST_DEV)
              export DATABRICKS_TOKEN=$(DATABRICKS_TOKEN_DEV)
              databricks version
              databricks bundle validate --target dev
            displayName: Validate (dev)

  - stage: Deploy_Dev
    displayName: Deploy to Dev
    dependsOn: Validate
    jobs:
      - deployment: deploy_dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # ✅ Instalar Databricks CLI (Go)
                - script: |
                    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
                    databricks version
                  displayName: Install Databricks CLI (Go)

                - script: |
                    export DATABRICKS_HOST=$(DATABRICKS_HOST_DEV)
                    export DATABRICKS_TOKEN=$(DATABRICKS_TOKEN_DEV)
                    databricks bundle deploy --target dev
                    databricks bundle run test_job --target dev
                  displayName: Deploy & Run (dev)

  - stage: Deploy_Prod
    displayName: Deploy to Prod
    dependsOn: Deploy_Dev
    jobs:
      - deployment: deploy_prod
        environment: prod   # Configura approvals/checks en este Environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # ✅ Instalar Databricks CLI (Go)
                - script: |
                    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
                    databricks version
                  displayName: Install Databricks CLI (Go)

                - script: |
                    export DATABRICKS_HOST=$(DATABRICKS_HOST_PROD)
                    export DATABRICKS_TOKEN=$(DATABRICKS_TOKEN_PROD)
                    databricks bundle validate --target prod
                    databricks bundle deploy --target prod
                    # Opcional: correr post-deploy
                    databricks bundle run etl_job --target prod
                  displayName: Deploy & (optional) Run (prod)